import { PrismaClient } from '@prisma/client';
import { MONTH_LABELS, COST_PER_READMISSION, MONTHLY_DECISIONS } from './constants';

export async function seedMetrics(prisma: PrismaClient) {
  // Monthly metrics showing improvement over 6 months
  const metrics = [
    {
      month_number: 1,
      month_label: MONTH_LABELS[0],
      total_decisions: MONTHLY_DECISIONS,
      decisions_with_context_match: 45,
      total_with_outcomes: 2400,
      successes: 1560,
      readmissions: 413,
      readmission_rate: 0.172,
      success_rate: 0.65,
      with_rich_context_success_rate: 0.78,
      without_rich_context_success_rate: 0.55,
      context_lift: 0.23,
      policy_followed_count: 2550,
      policy_followed_success: 0.68,
      exception_taken_count: 450,
      exception_taken_success: 0.52,
      active_patterns: 0,
      new_patterns: 0,
      cost_per_readmission: COST_PER_READMISSION,
      readmissions_avoided: 0,
      savings_this_month: 0,
      cumulative_savings: 0
    },
    {
      month_number: 2,
      month_label: MONTH_LABELS[1],
      total_decisions: MONTHLY_DECISIONS,
      decisions_with_context_match: 120,
      total_with_outcomes: 2450,
      successes: 1666,
      readmissions: 404,
      readmission_rate: 0.165,
      success_rate: 0.68,
      with_rich_context_success_rate: 0.80,
      without_rich_context_success_rate: 0.55,
      context_lift: 0.25,
      policy_followed_count: 2580,
      policy_followed_success: 0.70,
      exception_taken_count: 420,
      exception_taken_success: 0.55,
      active_patterns: 1,
      new_patterns: 1,
      cost_per_readmission: COST_PER_READMISSION,
      readmissions_avoided: 21,
      savings_this_month: 319200,
      cumulative_savings: 319200
    },
    {
      month_number: 3,
      month_label: MONTH_LABELS[2],
      total_decisions: MONTHLY_DECISIONS,
      decisions_with_context_match: 280,
      total_with_outcomes: 2480,
      successes: 1761,
      readmissions: 392,
      readmission_rate: 0.158,
      success_rate: 0.71,
      with_rich_context_success_rate: 0.82,
      without_rich_context_success_rate: 0.55,
      context_lift: 0.27,
      policy_followed_count: 2610,
      policy_followed_success: 0.73,
      exception_taken_count: 390,
      exception_taken_success: 0.58,
      active_patterns: 2,
      new_patterns: 1,
      cost_per_readmission: COST_PER_READMISSION,
      readmissions_avoided: 42,
      savings_this_month: 638400,
      cumulative_savings: 957600
    },
    {
      month_number: 4,
      month_label: MONTH_LABELS[3],
      total_decisions: MONTHLY_DECISIONS,
      decisions_with_context_match: 450,
      total_with_outcomes: 2500,
      successes: 1850,
      readmissions: 375,
      readmission_rate: 0.150,
      success_rate: 0.74,
      with_rich_context_success_rate: 0.83,
      without_rich_context_success_rate: 0.55,
      context_lift: 0.28,
      policy_followed_count: 2640,
      policy_followed_success: 0.76,
      exception_taken_count: 360,
      exception_taken_success: 0.62,
      active_patterns: 3,
      new_patterns: 1,
      cost_per_readmission: COST_PER_READMISSION,
      readmissions_avoided: 66,
      savings_this_month: 1003200,
      cumulative_savings: 1960800
    },
    {
      month_number: 5,
      month_label: MONTH_LABELS[4],
      total_decisions: MONTHLY_DECISIONS,
      decisions_with_context_match: 620,
      total_with_outcomes: 2520,
      successes: 1940,
      readmissions: 358,
      readmission_rate: 0.142,
      success_rate: 0.77,
      with_rich_context_success_rate: 0.84,
      without_rich_context_success_rate: 0.55,
      context_lift: 0.29,
      policy_followed_count: 2670,
      policy_followed_success: 0.79,
      exception_taken_count: 330,
      exception_taken_success: 0.65,
      active_patterns: 4,
      new_patterns: 1,
      cost_per_readmission: COST_PER_READMISSION,
      readmissions_avoided: 90,
      savings_this_month: 1368000,
      cumulative_savings: 3328800
    },
    {
      month_number: 6,
      month_label: MONTH_LABELS[5],
      total_decisions: MONTHLY_DECISIONS,
      decisions_with_context_match: 800,
      total_with_outcomes: 2550,
      successes: 2040,
      readmissions: 344,
      readmission_rate: 0.135,
      success_rate: 0.80,
      with_rich_context_success_rate: 0.85,
      without_rich_context_success_rate: 0.55,
      context_lift: 0.30,
      policy_followed_count: 2700,
      policy_followed_success: 0.82,
      exception_taken_count: 300,
      exception_taken_success: 0.68,
      active_patterns: 4,
      new_patterns: 0,
      cost_per_readmission: COST_PER_READMISSION,
      readmissions_avoided: 111,
      savings_this_month: 1687200,
      cumulative_savings: 5016000
    }
  ];

  await prisma.dCG_MonthlyMetrics.createMany({ data: metrics });
  console.log('Created monthly metrics');
}
